# Project Name:       COVID-19 Care: Face Mask and Social Distancing Detection using Deep Learning
# Author List:        Generated by Django
# Filename:           apps.py
# Functions:          No functions.
# Global Variables:   NA

from django.apps import AppConfig


class AccountConfig(AppConfig):
    name = 'account'
