# Project Name:       COVID-19 Care: Face Mask and Social Distancing Detection using Deep Learning
# Author List:        Generated by Django
# Filename:           admin.py
# Functions:          No functions. This file registers the database models of the social distancing module
#                     for the admin panel
# Global Variables:   NA

from django.contrib import admin
from .models import Video

# Register your models here.
admin.site.register(Video)