# Generated by Django 3.1.1 on 2020-10-21 08:59

#  Project Name: 	    COVID-19 Care: Face Mask and Social Distancing Detection using Deep Learning
#  Author List: 	    Auto generated by Django
#  Filename: 		    0002_previous_mask_previous_social.py
#  Functions: 		    No functions, one class which represents the database migrations
#  Global Variables:	NA

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previous_Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Previous_Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('result', models.IntegerField()),
            ],
        ),
    ]
