# Generated by Django 3.1.1 on 2020-10-21 12:53

#  Project Name: 	    COVID-19 Care: Face Mask and Social Distancing Detection using Deep Learning
#  Author List: 	    Auto generated by Django
#  Filename: 		    0003_auto_20201021_1823.py
#  Functions: 		    No functions, one class which represents the database migrations
#  Global Variables:	NA

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_previous_mask_previous_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='previous_mask',
            name='category',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='previous_social',
            name='category',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
