# Generated by Django 3.1.1 on 2020-10-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_previous_mask_previous_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='previous_mask',
            name='category',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='previous_social',
            name='category',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
