# Generated by Django 3.1.1 on 2020-10-21 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201021_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_mask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 13, 30, 57, 57926, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='previous_social',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 13, 30, 57, 58923, tzinfo=utc)),
        ),
    ]
