# Generated by Django 3.1.2 on 2020-10-25 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201021_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='previous_mask',
            name='location',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='previous_social',
            name='location',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='previous_mask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 12, 10, 40, 26310, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='previous_social',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 12, 10, 40, 26672, tzinfo=utc)),
        ),
    ]
