# Generated by Django 3.1.2 on 2020-10-25 12:16

#  Project Name: 	    COVID-19 Care: Face Mask and Social Distancing Detection using Deep Learning
#  Author List: 	    Auto generated by Django
#  Filename: 		    0006_auto_20201021_1746.py
#  Functions: 		    No functions, one class which represents the database migrations
#  Global Variables:	NA

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201025_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_mask',
            name='location',
            field=models.CharField(default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='previous_mask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 12, 16, 38, 68410, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='previous_social',
            name='location',
            field=models.CharField(default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='previous_social',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 12, 16, 38, 68781, tzinfo=utc)),
        ),
    ]
