# Generated by Django 3.1.2 on 2020-10-25 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201025_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='previous_mask',
            options={'verbose_name_plural': 'Previous Mask Records'},
        ),
        migrations.AlterModelOptions(
            name='previous_social',
            options={'verbose_name_plural': 'Previous Social Distancing Records'},
        ),
        migrations.AlterField(
            model_name='previous_mask',
            name='result',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='previous_mask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 12, 42, 36, 994744, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='previous_social',
            name='category',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='previous_social',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 12, 42, 36, 995139, tzinfo=utc)),
        ),
    ]
