# Generated by Django 3.1.2 on 2020-10-27 05:18

#  Project Name: 	    COVID-19 Care: Face Mask and Social Distancing Detection using Deep Learning
#  Author List: 	    Auto generated by Django
#  Filename: 		    0008_auto_20201027_1048.py
#  Functions: 		    No functions, one class which represents the database migrations
#  Global Variables:	NA

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201025_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_mask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 5, 18, 54, 474679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='previous_social',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 5, 18, 54, 475081, tzinfo=utc)),
        ),
    ]
