# Generated by Django 3.1.3 on 2021-03-20 12:52

#  Project Name: 	    COVID-19 Care: Face Mask and Social Distancing Detection using Deep Learning
#  Author List: 	    Auto generated by Django
#  Filename: 		    0010_auto_20210320_1822.py
#  Functions: 		    No functions, one class which represents the database migrations
#  Global Variables:	NA

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201027_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_mask',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 12, 52, 11, 142099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='previous_social',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 12, 52, 11, 143099, tzinfo=utc)),
        ),
    ]
