# Project Name:       COVID-19 Care: Face Mask and Social Distancing Detection using Deep Learning
# Author List:        Generated by Django
# Filename:           admin.py
# Functions:          No functions. This file is used to register the models for mask app
# Global Variables:   NA


from django.contrib import admin
from .models import Video
# Register your models here.

admin.site.register(Video)