# Project Name:       COVID-19 Care: Face Mask and Social Distancing Detection using Deep Learning
# Author List:        Generated by Django
# Filename:           models.py
# Functions:          No functions. This file represnts the database model for storing the videos uploaded 
#                     for mask detection
# Global Variables:   NA

from django.db import models

# Create your models here.
class Video(models.Model):
    video = models.FileField(upload_to='mask_videos/')
    
    #def __str__(self):
    #    return self.id
    
    class Meta:
        verbose_name_plural = 'Videos'