# Project Name:       COVID-19 Care: Face Mask and Social Distancing Detection using Deep Learning
# Author List:        Generated by Django
# Filename:           tests.py
# Functions:          No functions.
# Global Variables:   NA

from django.test import TestCase

# Create your tests here.
