# Generated by Django 3.1.2 on 2020-10-27 05:18

# Project Name:       COVID-19 Care: Face Mask and Social Distancing Detection using Deep Learning
# Author List:        Generated by Django
# Filename:           0001_initial.py
# Functions:          No functions. One class that represents the database model
# Global Variables:   NA

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
