# Generated by Django 3.1.3 on 2021-03-20 12:52

# Project Name:       COVID-19 Care: Face Mask and Social Distancing Detection using Deep Learning
# Author List:        Generated by Django
# Filename:           0002_auto_20210320_1822.py
# Functions:          No functions. One class that represents the database model
# Global Variables:   NA

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='mask_videos/'),
        ),
    ]
